webcau/avisos/urls.py
from django.urls import path
from . import views
from avisos.views.notices import MyNoticesView, AllNoticesView, DetailNoticeView, CreateShortNoticeView, UpdateShortNoticeView, MemberAutocomplete, CarsAutocomplete, FriendsAutocomplete, SendNoticeView, ArrivedNoticeView, DeleteShortNoticeView, DuplicateShortNoticeView
from avisos.views.pdf_gen import PDFNoticeView
from avisos.views.base import IndexView

app_name = 'avisos'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('avisos/', AllNoticesView.as_view(), name='avisos'),
    path('avisos/misavisos/', MyNoticesView.as_view(), name='myavisos'),
    path('avisos/nuevo_rapido/', CreateShortNoticeView.as_view(), name='new_shortnotice'),
    path('avisos/nuevo_rapido/<int:pk>/', DuplicateShortNoticeView.as_view(), name='duplicate_shortnotice'),
    path('avisos/<int:pk>/editar', UpdateShortNoticeView.as_view(), name='edit_shortnotice'),
    path('avisos/<int:pk>/enviar', SendNoticeView.as_view(), name='send_shortnotice'),
    path('avisos/<int:pk>/eliminar', DeleteShortNoticeView.as_view(), name='delete_shortnotice'),
    path('avisos/<int:pk>/llegada', ArrivedNoticeView.as_view(), name='arrive_shortnotice'),
    path('avisos/<int:pk>/', DetailNoticeView.as_view(), name='detail_notice'),
    path('avisos/member_autocomplete/', MemberAutocomplete.as_view(), name='member_autocomplete'),
    path('avisos/cars_autocomplete/', CarsAutocomplete.as_view(), name='cars_autocomplete'),
    path('avisos/friends_autocomplete/', FriendsAutocomplete.as_view(), name='friends_autocomplete'),
    path('avisos/<int:pk>/pdf', views.PDFNoticeView, name='pdf_notice'),
]

webcau/webcau/urls.py
from django.contrib import admin
from django.urls import include, path
from avisos.views.base import IndexView
from avisos.views.account import UpdateAccountView, UpdateMedicalView, CarsView, CreateCarView, UpdateCarView, DeleteCarView, EmergencyContactsView, CreateEmergencyContactView, UpdateEmergencyContactView, DeleteEmergencyContactView, FriendsView, CreateFriendView, UpdateFriendView, DeleteFriendView
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acceso/', include('django.contrib.auth.urls')),
    path('', include('avisos.urls')),
    path('', IndexView.as_view(), name='index'),
    path('cuenta/panel', UpdateAccountView.as_view(), name='account_data'),
    path('cuenta/salud/', UpdateMedicalView.as_view(), name='medical_data'),
    path('cuenta/vehiculos/', CarsView.as_view(), name='cars_data'),
    path('cuenta/vehiculos/nuevo', CreateCarView.as_view(), name='new_car'),
    path('cuenta/vehiculos/<int:pk>/', UpdateCarView.as_view(), name='edit_car'),
    path('cuenta/vehiculos/<int:pk>/eliminar', DeleteCarView.as_view(), name='delete_car'),
    path('cuenta/contactos/', EmergencyContactsView.as_view(), name='emergencycontacts_data'),
    path('cuenta/contactos/nuevo', CreateEmergencyContactView.as_view(), name='new_emergencycontact'),
    path('cuenta/contactos/<int:pk>/', UpdateEmergencyContactView.as_view(), name='edit_emergencycontact'),
    path('cuenta/contactos/<int:pk>/eliminar', DeleteEmergencyContactView.as_view(), name='delete_emergencycontact'),
    path('cuenta/amigos/', FriendsView.as_view(), name='friends_data'),
    path('cuenta/amigos/nuevo', CreateFriendView.as_view(), name='new_friend'),
    path('cuenta/amigos/<int:pk>/', UpdateFriendView.as_view(), name='edit_friend'),
    path('cuenta/amigos/<int:pk>/eliminar', DeleteFriendView.as_view(), name='delete_friend'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webcau/avisos/models/car.py
from .base import *
from .member import Member

class Car(SoftDeletionModel):
    member = models.ForeignKey(Member, on_delete=models.CASCADE, null=True, blank=True)
    alias = models.CharField(max_length=100)
    brand = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    year = models.IntegerField()
    color = models.CharField(max_length=100)
    license_plate = models.CharField(max_length=100)

    class Meta:
        verbose_name = "Vehículo"
        verbose_name_plural = "Vehículos"
        ordering = ['member', 'alias']

    def delete(self):
      self.member = None
      self.save()

    def __str__(self):
        if self.member:
            if self.alias:
                return str(self.member.name) +  " - " + str(self.alias) + " - " + str(self.license_plate)
            else:
                return " - " + str(self.member.name) + " - " + str(self.license_plate)
        else:
            return " - "

webcau/avisos/models/notice.py
from datetime import timedelta
from django.db.models.signals import post_save
import celery
from django.dispatch import receiver
from django.utils import timezone as tz
from django.core.mail import send_mail, EmailMessage
from .base import *
from .member import Member, EmailRecipient, ClubBoard, Friend, ClubBoardMember
from .car import Car
import io
from .global_settings import *
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle, HRFlowable, ListFlowable, ListItem, PageBreak
from reportlab.lib import colors
from reportlab.pdfbase.pdfmetrics import stringWidth
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.core.mail import EmailMultiAlternatives
from django.conf import settings

def datetime_now_rounder():
    if tz.now().hour == 22:
        return tz.now().replace(hour=23, minute=0, second=0, microsecond=0)
    elif tz.now().hour == 23:
        temp_time = tz.now() + timedelta(days=1)
        return temp_time.replace(hour=0, minute=0, second=0, microsecond=0)
    else:
        return tz.now().replace(hour=tz.now().hour + 1, minute=0, second=0, microsecond=0)
    
class NoticeCategory(SoftDeletionModel):
  name = models.CharField(max_length=100)
  priority = models.IntegerField(default=0)
  
  class Meta:
    verbose_name = "Categoría de aviso"
    verbose_name_plural = "Categorías de avisos"
    ordering = ['priority']
  
  def __str__(self):
      return self.name

class BaseNotice(SoftDeletionModel):
    location = models.CharField(max_length=100)
    route = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    DRAFT = 0
    PUBLISHED = 1
    ACTIVE = 2
    LATE = 3
    ARRIVED = 4
    CANCELLED = 5
    STATUS_CHOICES = (
        (DRAFT, 'Borrador'),
        (PUBLISHED, 'Publicado'),
        (ACTIVE, 'Activo'),
        (LATE, 'Retrasado'),
        (ARRIVED, 'Llegado'),
        (CANCELLED, 'Cancelado'),
    )
    status = models.IntegerField(choices=STATUS_CHOICES, default=DRAFT)
    category = models.ForeignKey(NoticeCategory, on_delete=models.CASCADE)
    start_date = models.DateTimeField(default=datetime_now_rounder, blank=True)
    max_end_date = models.DateTimeField(default=datetime_now_rounder, blank=True)
    participants = models.ManyToManyField(Member, blank=True)
    friends = models.ManyToManyField(Friend, blank=True)
    cars = models.ManyToManyField(Car, blank=True)
    parking_location = models.CharField(max_length=100, blank=True)
    cau_contact = models.ForeignKey(Member, on_delete=models.CASCADE, related_name="cau_contact", blank=True, null=True)
    other_transportation = models.CharField(max_length=100, blank=True, null=True)

    email_recipients = models.ManyToManyField(EmailRecipient, blank=True, related_name="email_recipients")
    email_late_alert_recipients = models.ManyToManyField(EmailRecipient, blank=True, related_name="email_late_alert_recipients")
    sent_date = models.DateTimeField(null=True, blank=True)
    sent_by = models.ForeignKey(Member, on_delete=models.CASCADE, related_name="sent_by", blank=True, null=True)
    arrival_confirmation_date = models.DateTimeField(null=True, blank=True)
    arrival_confirmation_by = models.ForeignKey(Member, on_delete=models.CASCADE, related_name="arrival_confirmation_by", blank=True, null=True)
    include_pdf = models.BooleanField(default=True)

    arrival_message = models.TextField(blank=True, null=True)
    arrival_result = models.TextField(blank=True, null=True)
    arrival_conditions = models.TextField(blank=True, null=True)
    
    class Meta:
        verbose_name = 'Aviso'
        verbose_name_plural = 'Avisos'
        ordering = ['-start_date']

    def __str__(self):
        return str(self.start_date.date()) + " - " + self.category.name + ": " + self.location + " - " + self.route

    def participants_tostring(self):
        return ", ".join([", ".join([str(member) for member in self.participants.all()]), ", ".join([str(friend) for friend in self.friends.all()])])

    def start_celery_task(self, number):
        if number == 1:
            print("vamos a empezar la espera hasta start_date" + str(self.start_date))
            celery.current_app.send_task(name='avisos.tasks.wait_for_start_time', args=(self.id,), eta=self.start_date)
            print("ya hemos empezado la espera hasta start_date"+ str(self.start_date))
        elif number == 2:
            print("vamos a empezar la espera hasta fin máximo")
            celery.current_app.send_task(name='avisos.tasks.wait_for_max_end_time', args=(self.id,), eta=self.max_end_date)
            print("ya hemos empezado la espera hasta fin máximo")

    def allowed_to_see(self):
        if self.status == self.DRAFT:
            return list(self.participants.all()) + [self.cau_contact]
        else:
          return Member.objects.all()

    def allowed_to_edit(self):
        return list(self.participants.all()) + [self.cau_contact]

    def include_email(self, email, late_alert=False):
        if email == "" or email is None:
            return
        if EmailRecipient.objects.filter(email=email).exists():
            self.email_recipients.add(EmailRecipient.objects.filter(email=email).first())
            if late_alert:
                self.email_late_alert_recipients.add(EmailRecipient.objects.filter(email=email).first())
        else:
            self.email_recipients.add(EmailRecipient.objects.create(email=email))
            if late_alert:
                self.email_late_alert_recipients.add(EmailRecipient.objects.create(email=email))

    def include_caucontacts(self):
        if self.cau_contact:
            self.include_email(self.cau_contact.user.email, True)

    def include_participants(self):
        for member in self.participants.all():
            self.include_email(member.user.email, True)
        for friend in self.friends.all():
            self.include_email(friend.email, True)

    def include_board(self):
        if ClubBoard.objects.count() > 0:
            for member in ClubBoard.objects.first().members.all():
                # check if clubboardmembers that have this member receivenotices
                clubboardmember = ClubBoardMember.objects.filter(member=member).first()
                if clubboardmember and clubboardmember.receivenotices:
                    self.include_email(member.user.email, True)
    
    def include_emergencycontacts(self):
        for member in self.participants.all():
            if member.main_emergencycontact:
                self.include_email(member.main_emergencycontact.email, False)
        for friend in self.friends.all():
            if friend.emergencycontact_email:
                self.include_email(friend.emergencycontact_email, False)

    def include_caumembers(self):
      if GlobalSettings.objects.count() > 0:
        if GlobalSettings.objects.first().group_mail:
          self.include_email(GlobalSettings.objects.first().group_mail, False)

    def publish_notice(self, mail_content=None):
        # Crear Validadores
        celery.current_app.send_task(name='avisos.tasks.enqueue_mail', args=(self.id, True, False, False, False, mail_content))
        if tz.now() >= self.max_end_date:
            # Confirmar que queremos hacer esto
            self.late_notice()
        elif tz.now() >= self.start_date:
            self.activate_notice()
        else:
            self.start_celery_task(1)
            self.status = self.PUBLISHED
            self.save()
    
    def activate_notice(self):
        if tz.now() >= self.max_end_date:
            # Confirmar que queremos hacer esto
            self.late_notice()
        elif tz.now() >= self.start_date:
            self.status = self.ACTIVE
            self.save()
            self.start_celery_task(2)

    def late_notice(self):
        if tz.now() >= self.max_end_date and self.status == self.ACTIVE:
            self.status = self.LATE
            self.save()
            celery.current_app.send_task(name='avisos.tasks.enqueue_mail', args=(self.id, False, False, True, False, None))
        elif tz.now() >= self.max_end_date:
            self.status = self.LATE
            self.save()

    def notify_arrival(self):
        if self.status != self.ARRIVED:
            self.status = self.ARRIVED
            self.save()
            celery.current_app.send_task(name='avisos.tasks.enqueue_mail', args=(self.id, False, True, False, False, None))


    def cancel_notice(self):
        self.status = self.CANCELLED
        self.save()
        # celery.current_app.send_task(name='avisos.tasks.enqueue_mail', args=(self.id, False, False, False, True, None))

    
    ###############################################################################
    #                                  PDF Files                                  #
    ###############################################################################
    def createPDF(self, buff, pdf_name):
        doc = SimpleDocTemplate(buff, title=pdf_name, pagesize=letter, rightMargin=24, leftMargin=24, topMargin=72, bottomMargin=18)

        styles = getSampleStyleSheet()
        styles.add(ParagraphStyle(name='main_title', alignment=TA_CENTER, fontName='Helvetica-Bold', fontSize=14, leading=14))
        styles.add(ParagraphStyle(name='subtitles', fontName='Helvetica-Bold', fontSize=11, leading=11))
        styles.add(ParagraphStyle(name='notice_bold', fontName='Helvetica-Bold', fontSize=10, leading=10))
        styles.add(ParagraphStyle(name='notice', fontName='Helvetica', fontSize=10, leading=10))
        styles.add(ParagraphStyle(name='final_content', fontName='Helvetica', fontSize=9, leading=9))

webcau/avisos/views/base.py
from django.shortcuts import render
from django.views import View
from ..models import Member, Car, EmergencyContact, BaseNotice
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Q

class IndexView(LoginRequiredMixin, View):
    
    def get(self, request):
        return render(request, 'index.html', {'member': self.get_object(), 'cars': self.get_cars(), 'emergencycontacts': self.get_emergencycontacts(), 'active_notices': self.get_active_notices()})
    def get_object(self):
        return Member.objects.get(user=self.request.user)
    
    def get_cars(self):
        return Car.objects.filter(member=self.get_object())
    
    def get_emergencycontacts(self):
        return EmergencyContact.objects.filter(member=self.get_object())
    
    def get_active_notices(self):
        return [notice for notice in BaseNotice.objects.filter(Q(status=2) | Q(status=3)) if self.get_object() in notice.allowed_to_edit()]



class ObjectOwnerAuthMixin(LoginRequiredMixin, UserPassesTestMixin):
    def test_func(self):
        return self.get_object().member == self.request.user.member

###############################################################################
#                         Mixin para modals con ajax                          #
###############################################################################
class AjaxTemplateMixin(object):
    def dispatch(self, request, *args, **kwargs):
        if not hasattr(self, 'ajax_template_name'):
            split = self.template_name.split('.html')
            split[-1] = '_inner'
            split.append('.html')
            self.ajax_template_name = ''.join(split)
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            self.template_name = self.ajax_template_name
        return super(AjaxTemplateMixin, self).dispatch(request, *args, **kwargs)

webcau/avisos/views/pdf_gen.py
from ..models import ShortNotice
from django.http import HttpResponse
import io
from django.shortcuts import get_object_or_404

def PDFNoticeView(request, pk):
    buff = io.BytesIO()
    notice = get_object_or_404(ShortNotice, pk=pk)
    pdf_name = "Aviso de Salida - " + notice.location
    pdf_name = pdf_name.replace(',', ' - ')

    doc = notice.createPDF(buff, pdf_name)

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename=' + pdf_name + '.pdf'
    response.write(buff.getvalue())

    buff.close()
    return response

webcau/avisos/templates/avisos/shortnotice/arrival.html
{% extends "headers.html" %}
{% load static %}

{% block content %}
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
        <strong {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
  {% endif %}
  <div class="container justify-content-md-center text-dark">
    <div class="row">
      <h4 class="mt-4 mb-3">Notificar Llegada</h4>
    </div>
    <div class="row">
      <p class="mt-3" style="width:25rem; margin:auto;">Recuerda que la llegada se debe notificar una vez que haya confirmación de que la cordada está a salvo en el transporte de regreso o en sus casas.</p>
    </div>     
    <div class="row justify-content-md-center p-3 m-3 rounded row-form">
      <div class="form-group" style="width:25rem;">
        <form method="post" style="text-align: center;">
          {% csrf_token %}
          {% for field in form %}
            <p style="text-align: left; display: block !important;">
              {{ field.label_tag }} {% if field.field.required %}<span class="text-danger">*</span> {% endif %}    
              <span class="field-info"><i class="fa-solid fa-lg fa-circle-question text-info" style="text-align:right;" data-toggle="tooltip" data-placement="top" title="{{ field.field.help_text }}"></i></span>
              {{ field.errors }}

              {{ field }}
            </p>
          {% endfor %}
          <table style="display: none">
            {{ view.formset.empty_form }}
          </table>

          <table>
              {{ view.formset }}
          </table>
          <button type="submit" class="btn btn-warning mb-3">Confirmar</button>
        </form>
      </div>
    </div>
  </div>
    
{% endblock %}

webcau/avisos/templates/avisos/shortnotice/delete.html
{% extends "headers.html" %}
{% load static %}

{% block content %}
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
        <strong {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
  {% endif %}
  <div class="container justify-content-md-center text-dark">
    <div class="row">
      <h4 class="mt-4 mb-3">Eliminar aviso</h4>
    </div>
    <div class="row">
      <p class="mt-3" style="width:25rem; margin:auto;">¿Estás seguro que deseas eliminar este aviso de salida?</p>
    </div>     
    <div class="row justify-content-md-center rounded text-start mt-5">
      <div class="form-group" style="width:25rem;">
        <form method="post" style="text-align: center;">
          {% csrf_token %}
          <button type="submit" class="btn btn-primary mb-3">Confirmar</button>
        </form>
      </div>
    </div>
  </div>
    
{% endblock %}

webcau/avisos/templates/avisos/shortnotice/detail.html
{% extends "headers.html" %}
{% load static %}

{% block content %}
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
        <strong {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
  {% endif %}
  <div class="container justify-content-md-center text-dark"  style="width:25rem; padding:0px;">
    <div class="row mt-4">  
      <h4 class="mt-1 mb-2">
        {{ aviso.shortnotice }}<br>
      </h4>
    </div>
    <div class="btn-group btn-group-lg mb-3" role="group" style="width:25rem;">
      {% if user.member in aviso.allowed_to_edit %}  
        {% if aviso.status == 0 %}
          <a class="btn btn-info" href="{% url 'avisos:send_shortnotice' aviso.id %}"><i class="bi-send-check-fill"></i> Publicar</a>
        {% elif aviso.status == 1 or aviso.status == 2 or aviso.status == 3 %}
          <a class="btn btn-info" href="{% url 'avisos:arrive_shortnotice' aviso.id %}"><i class="bi-geo-alt-fill"></i> Avisar Llegada</a>
        {% endif %}
        <a class="btn btn-light" href="{% url 'avisos:edit_shortnotice' aviso.id %}"><i class="bi-pencil-square"></i> Editar</a>
        {% if aviso.status == 0 %}
          <a class="btn btn-light" href="{% url 'avisos:delete_shortnotice' aviso.id %}"><i class="bi-trash"></i> Eliminar</a>
        {% endif %}
        <a class="btn btn-light" href="{% url 'avisos:duplicate_shortnotice' aviso.id %}"><i class="bi-node-plus"></i> Duplicar</a>
      {% endif %}
    </div>
    <div class="btn-group btn-group-lg mb-3" role="group" style="width:25rem;">
      <a class="btn btn-light" href="{% url 'avisos:pdf_notice' aviso.id %}"><i class="bi-download"></i> PDF</a>    
    </div>
  </div>

  <div class="row justify-content-md-center p-3 rounded">
    <div style="width:25rem;">
      
      <h6>Fecha Máxima de Llegada: </h6><h5>{{ aviso.max_end_date|date:"H:i - d/m/Y" }}</h5>
      {% if aviso.time_left_for_arrival <= 0 and aviso.status < 4 %}
        <p><b>Llegada Atrasada</b></p>
      {% endif %}
      <h4 class="mb-3">
        {% if aviso.status == 0 %}
            <span class="badge bg-light">
          {% elif aviso.status == 1 %}
            <span class="badge bg-primary">
          {% elif aviso.status == 2 %}
            <span class="badge bg-secondary">
          {% elif aviso.status == 3 %}
            <span class="badge bg-info">
          {% elif aviso.status == 4 %}
            <span class="badge bg-success">
          {% elif aviso.status == 5 %}
            <span class="badge bg-light">
          {% endif %}
          {{ aviso.get_status_display }}</span>
      </h4>
      <table class="table table-sm mt-3">
        <tbody>
          <tr>
            <th scope="row">Categoría</th>
            <td>{{ aviso.category }}</td>
          </tr>
          <tr>
            <th scope="row">Lugar</th>
            <td>{{ aviso.shortnotice.location }}</td>
          </tr>
          <tr>
            <th scope="row">Ruta</th>
            <td>{{ aviso.shortnotice.route }}</td>
          </tr>
          <tr>
            <th scope="row">Fecha de Salida</th>
            <td>{{ aviso.shortnotice.start_date|date:"d/m/Y" }}</td>
          </tr>
          <tr>
            <th scope="row">Hora de Salida</th>
            <td>{{ aviso.shortnotice.start_date|date:"H:i" }}</td>
          <tr>
            <th scope="row">Contacto CAU</th>
            <td>{{ aviso.cau_contact }}</td>
          </tr>
          <tr>
            <th scope="row">Transporte Vehicular</th>
            <td>
              {% if aviso.cars %}
                {% for car in aviso.cars.all %}
                  {{ car.brand }} - {{ car.model }}<br>
                {% endfor %}
              {% endif %}
              {% if aviso.other_transportation %}
                {{ aviso.other_transportation }}
              {% endif %}
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="row justify-content-md-center table-responsive" style="">
      <table class="table table-lg" style="text-align:left;">
        <thead class="table-dark">
          <tr>
            <th scope="col" colspan="2" style="border-right: 1px white solid; text-align: center;">Cordada</th>
            <th scope="col" colspan="4" style="text-align: center;">Contacto de Emergencia</th>
          </tr>
        </thead>
        <thead>
          <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Teléfono</th>
            <th scope="col">Nombre Contacto</th>
            <th scope="col">Teléfono Contacto</th>
            <th scope="col">Email Contacto</th>
            <th scope="col">Parentesco Contacto</th>
          </tr>
        </thead>
        <tbody>
          {% for member in aviso.participants.all %}
            <tr>
              <td>{{ member }}</td>
              <td>{{ member.phone_number }}</td>
              <td>{{ member.main_emergencycontact }}</td>
              <td>{{ member.main_emergencycontact.phone_number }}</td>
              <td>{{ member.main_emergencycontact.email }}</td>
              <td>{{ member.main_emergencycontact.relationship }}</td>
            </tr>
          {% endfor %}
          {% for friend in aviso.friends.all %}
            <tr>
              <td>{{ friend }}</td>
              <td>{{ friend.phone_number }}</td>
              <td>{{ friend.emergencycontact_name }}</td>
              <td>{{ friend.emergencycontact_phone }}</td>
              <td>{{ friend.emergencycontact_email }}</td>
              <td>{{ friend.emergencycontact_relationship }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>

      <table class="table table-sm">
        <thead class="table-dark">
          <tr>
            <th scope="col" colspan="6" style="text-align: center;">Vehículos</th>
          </tr>
        </thead>
        <thead>
          <tr>
            <th scope="col">Socio</th>
            <th scope="col">Marca</th>
            <th scope="col">Modelo</th>
            <th scope="col">Color</th>
            <th scope="col">Lugar de estacionamiento</th>
          </tr>
        </thead>
        <tbody>
          {% for car in aviso.cars.all %}
            <tr>
              <td>{{ car.member }}</td>
              <td>{{ car.brand }}</td>
              <td>{{ car.model }}</td>
              <td>{{ car.color }}</td>
              <td>{{ aviso.parking_location }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>

     <table class="table table-sm">
        <thead class="table-dark">
          <tr>
            <th scope="col" colspan="4" style="text-align: center;">Información Médica</th>
          </tr>
        </thead>
        <thead>
          <tr>
            <th scope="col">Socio</th>
            <th scope="col">Enfermedades</th>
            <th scope="col">Medicamentos</th>
            <th scope="col">Comentarios</th>
          </tr>
        </thead>
        <tbody>
          {% for member in aviso.participants.all %}
            {% if not member.medicalrecord.no_medical_record %}
              <tr>
                <td>{{ member }}</td>
                <td>{{ member.medicalrecord.sicknesses }}</td>
                <td>{{ member.medicalrecord.medications }}</td>
                <td>{{ member.medicalrecord.comments }}</td>
              </tr>
            {% endif %}
          {% endfor %}
          {% for friend in aviso.friends.all %}
            <tr>
              <td>{{ friend }}</td>
              <td>{{ friend.sicknesses }}</td>
              <td>{{ friend.medications }}</td>
              <td>{{ friend.comments }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>



 
{% endblock %}