webcau/avisos/urls.py
from django.urls import path
from . import views
from avisos.views.notices import MyNoticesView, AllNoticesView, DetailNoticeView, CreateShortNoticeView, UpdateShortNoticeView, MemberAutocomplete, CarsAutocomplete, FriendsAutocomplete, SendNoticeView, ArrivedNoticeView, DeleteShortNoticeView, DuplicateShortNoticeView
from avisos.views.pdf_gen import PDFNoticeView
from avisos.views.base import IndexView

app_name = 'avisos'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('avisos/', AllNoticesView.as_view(), name='avisos'),
    path('avisos/misavisos/', MyNoticesView.as_view(), name='myavisos'),
    path('avisos/nuevo_rapido/', CreateShortNoticeView.as_view(), name='new_shortnotice'),
    path('avisos/nuevo_rapido/<int:pk>/', DuplicateShortNoticeView.as_view(), name='duplicate_shortnotice'),
    path('avisos/<int:pk>/editar', UpdateShortNoticeView.as_view(), name='edit_shortnotice'),
    path('avisos/<int:pk>/enviar', SendNoticeView.as_view(), name='send_shortnotice'),
    path('avisos/<int:pk>/eliminar', DeleteShortNoticeView.as_view(), name='delete_shortnotice'),
    path('avisos/<int:pk>/llegada', ArrivedNoticeView.as_view(), name='arrive_shortnotice'),
    path('avisos/<int:pk>/', DetailNoticeView.as_view(), name='detail_notice'),
    path('avisos/member_autocomplete/', MemberAutocomplete.as_view(), name='member_autocomplete'),
    path('avisos/cars_autocomplete/', CarsAutocomplete.as_view(), name='cars_autocomplete'),
    path('avisos/friends_autocomplete/', FriendsAutocomplete.as_view(), name='friends_autocomplete'),
    path('avisos/<int:pk>/pdf', views.PDFNoticeView, name='pdf_notice'),
]

webcau/webcau/urls.py
from django.contrib import admin
from django.urls import include, path
from avisos.views.base import IndexView
from avisos.views.account import UpdateAccountView, UpdateMedicalView, CarsView, CreateCarView, UpdateCarView, DeleteCarView, EmergencyContactsView, CreateEmergencyContactView, UpdateEmergencyContactView, DeleteEmergencyContactView, FriendsView, CreateFriendView, UpdateFriendView, DeleteFriendView
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acceso/', include('django.contrib.auth.urls')),
    path('', include('avisos.urls')),
    path('', IndexView.as_view(), name='index'),
    path('cuenta/panel', UpdateAccountView.as_view(), name='account_data'),
    path('cuenta/salud/', UpdateMedicalView.as_view(), name='medical_data'),
    path('cuenta/vehiculos/', CarsView.as_view(), name='cars_data'),
    path('cuenta/vehiculos/nuevo', CreateCarView.as_view(), name='new_car'),
    path('cuenta/vehiculos/<int:pk>/', UpdateCarView.as_view(), name='edit_car'),
    path('cuenta/vehiculos/<int:pk>/eliminar', DeleteCarView.as_view(), name='delete_car'),
    path('cuenta/contactos/', EmergencyContactsView.as_view(), name='emergencycontacts_data'),
    path('cuenta/contactos/nuevo', CreateEmergencyContactView.as_view(), name='new_emergencycontact'),
    path('cuenta/contactos/<int:pk>/', UpdateEmergencyContactView.as_view(), name='edit_emergencycontact'),
    path('cuenta/contactos/<int:pk>/eliminar', DeleteEmergencyContactView.as_view(), name='delete_emergencycontact'),
    path('cuenta/amigos/', FriendsView.as_view(), name='friends_data'),
    path('cuenta/amigos/nuevo', CreateFriendView.as_view(), name='new_friend'),
    path('cuenta/amigos/<int:pk>/', UpdateFriendView.as_view(), name='edit_friend'),
    path('cuenta/amigos/<int:pk>/eliminar', DeleteFriendView.as_view(), name='delete_friend'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webcau/templates/full_settings.html
{% extends "headers.html" %}
{% load static %}

{% block content %}
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
        <strong {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
  {% endif %}
  <div class="container justify-content-md-center text-dark" id="app">
    <div class="row">
      <!-- Incluir foto de perfil y posibilidad de cambiarla -->
      <h4 class="mt-4 mb-3">{{ user.member }}</h4>
    </div>
    <div class="row">
      <div class="list-group list-group-horizontal">
        <a class="list-group-item flex-fill" :class="activeAccount" @click="changeToAccount" href="#"><i class="fa-solid fa-square-pen" style="font-size: 20px;"></i><p class="mb-1 list-group-item-title">Datos de cuenta</p></a>
        <a class="list-group-item flex-fill" :class="activePreferences" @click="changeToPreferences" href="#"><i class="fa-solid fa-gear" style="font-size: 20px;"></i><p class="mb-1 list-group-item-title">Preferencias</p></a>
        <a class="list-group-item flex-fill" :class="activeMedical" @click="changeToMedical" href="#"><i class="fa-solid fa-stethoscope" style="font-size: 20px;"></i><p class="mb-1 list-group-item-title">Datos Médicos</p></a>
        <a class="list-group-item flex-fill" :class="activeVehicles" @click="changeToVehicles" href="#"><i class="fa-solid fa-car" style="font-size: 20px;"></i><p class="mb-1 list-group-item-title">Vehículos</p></a>
      </div>
    </div>
    <div class="row justify-content-md-center p-3 m-3 bg-light rounded" style="min-height: 400px">
      <p> [[ title ]] </p>
      <div class="form-group" style="width:25rem;">
        <form v-if="account_is_active" method="post">
          {% csrf_token %}
          {{ form.account.as_p }}
          <button type="submit" class="btn btn-primary mb-3">Guardar</button>
        </form>
        <form v-if="preferences_is_active" method="post">
          {% csrf_token %}

          <button type="submit" class="btn btn-primary mb-3">Guardar</button>
        </form>
        <form v-if="medical_is_active" method="post">
          {% csrf_token %}
          {{ form.edit_medical.as_p }}
          <button type="submit" class="btn btn-primary mb-3">Guardar</button>
        </form>
        <form v-if="vehicles_is_active" method="post">

          <button type="submit" class="btn btn-primary mb-3">Guardar</button>
        </form>
      </div>
    </div>
  </div>

<script src="{% static 'js/app.js' %}"></script>


{% endblock %}

webcau/templates/headers.html
{% load static compress %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

        {% compress css %}
            <link rel="stylesheet" href="{% static 'scss/custom.scss' %}" type="text/x-scss" media="screen">
        {% endcompress %}

        {% compress js %}
            <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        {% endcompress %}
        <link rel="stylesheet" href="{% static 'fa/css/all.min.css' %}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
        <link rel="stylesheet" href="{% static 'css/jquery.multi-emails.css' %}">
        <script src="{% static 'js/htmx.min.js' %}"></script>     
        <script src="https://code.jquery.com/jquery-3.6.0.slim.min.js"></script>
        <script src="{% static 'js/jquery.multi-emails.js' %}"></script>   

        <meta name="description" content="Plataforma web Club Andino Universitario">
        <meta name="author" content="Damir Mandakovic">
        <title>CAU - Socios</title>
    </head>

    <body class="text-center">
        {% block nav %}{% include 'navbar.html' %}{% endblock nav %}
        <div class="container">

            {% block content %}
            {% endblock %}
        </div>
    </body>

</html>

webcau/templates/headers_error.html
{% load static %}
{% load compress %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
        {% compress css %}
            <link rel="stylesheet" href="{% static 'scss/custom.scss' %}" type="text/x-scss" media="screen">
        {% endcompress %}
        {% compress js %}
            <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
        {% endcompress %}
        <link rel="stylesheet" href="{% static 'fa/css/all.min.css' %}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
        <link rel="stylesheet" href="{% static 'css/jquery.multi-emails.css' %}">
        <script src="{% static 'js/htmx.min.js' %}"></script>     
        <script src="https://code.jquery.com/jquery-3.6.0.slim.min.js"></script>
        <script src="{% static 'js/jquery.multi-emails.js' %}"></script>   

        <meta name="description" content="Plataforma web Club Andino Universitario">
        <meta name="author" content="Damir Mandakovic">
        <title>CAU - Socios</title>
    </head>

    <body class="text-center">
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </body>

</html>

webcau/templates/index.html
{% extends "headers.html" %}

{% block content %}
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
        <strong {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
  {% endif %}

{% for aviso in active_notices %}
  {% if aviso.status == 2 %}
    <div class="card text-center mt-3">
  {% else %}
    <div class="card text-center mt-3 text-bg-info">
  {% endif %}
      <div class="card-header">
        Tienes una Salida {% if aviso.status == 2 %} Activa {% else %} ATRASADA {% endif %}
      </div>
      <div class="card-body" style="background: white; color: #1c1c1c;">
        <h5 class="card-title"><a class="" href="{% url 'avisos:detail_notice' aviso.id %}">Aviso de Salida: {{ aviso.shortnotice.location }}</a></h5>
        <p class="card-text">Si ya llegó la cordada, no te olvides de avisar la llegada.</p>
        <a class="btn btn-info" href="{% url 'avisos:arrive_shortnotice' aviso.id %}" data-toggle="tooltip" data-placement="top" title="Avisar Llegada"><i class="bi bi-house-fill"></i> Avisar Llegada</a>
      </div>
      {% if aviso.status == 2 %}
        <div class="card-footer text-muted">
      {% else %}
        <div class="card-footer text-muted" style="color: white !important;">
      {% endif %}
        Llegada Máxima: <h5>{{ aviso.max_end_date|date:"H:i - d/m/Y" }}</h5>
      </div>
  </div>
{% endfor %}

<h1 class="m-4">Accesos Directos</h1>
  {% if emergencycontacts.count == 0 %}  
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      Recuerda ingresar <strong>al menos un contacto de emergencia</strong> para poder crear tus avisos de salida.
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  {% endif %}
  {% if member.medicalrecord.pending %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <strong>Recuerda ingresar tu información médica</strong> para poder crear avisos de salida.
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  {% endif %}
  {% if cars is empty %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <strong>Recuerda ingresar los vehículos que usas</strong> para poder agregarlos a tus avisos de salida.
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  {% endif %}
<div class="container list-group" style="width:25rem;">
  <a href="{% url 'avisos:new_shortnotice' %}" class="list-group-item list-group-item-action">Aviso Rápido</a>
  <a class="list-group-item list-group-item-action disabled">Aviso Largo</a>
</div>

{% endblock %}

webcau/templates/navbar.html
{% load static %}
{% if not user.member.main_emergencycontact %}
  <div class="alert alert-danger" style="margin-bottom: 0px">
    No has definido a un contacto de emergencia como <strong><a href="{% url 'new_emergencycontact' %}">contacto predeterminado.</a></strong>
  </div>
{% endif %}
{% if user.member.medicalrecord.pending %}
  <div class="alert alert-danger" style="margin-bottom: 0px">
      No has completado tu <strong><a href="{% url 'medical_data' %}"> información médica. </a></strong>
  </div>
{% endif %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'index' %}">
        <img src="{% static 'images/logo_socioscau.png' %}" alt="Logo" class="navbar-brand" style="width: 100px">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item dropdown">
            <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Sistema de Avisos
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'avisos:new_shortnotice' %}">Aviso Rápido</a></li>
              <li><a class="dropdown-item disabled" href="#">Aviso Normal</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'avisos:myavisos' %}">Mis Avisos</a></li>
              <li><a class="dropdown-item" href="{% url 'avisos:avisos' %}">Avisos de Socios</a></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Beneficios CAU
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="https://docs.google.com/spreadsheets/d/1SHGlBRpMeVnzQUWHv42j0AYobRlDHRl0aLHvDyxGUqA/edit#gid=0">Biblioteca</a></li>
              <li><a class="dropdown-item" href="https://www.cau.cl/?page_id=3687">Descuentos</a></li>
              <li><a class="dropdown-item" href="https://www.cau.cl/?page_id=3902">Entrenamientos</a></li>
              <li><a class="dropdown-item" href="https://www.cau.cl/?page_id=76">Préstamo de Equipo</a></li>
              <li><a class="dropdown-item" href="https://www.cau.cl/?page_id=4648">InReach</a></li>
              <li><a class="dropdown-item" href="https://drive.google.com/file/d/123zxL-kwaBIJ4Mvs9v7hWPLNGl0JtHwo/view?usp=sharing">Manual de Socios</a></li>
              <li><hr class="dropdown-divider"></li>
              <!--<li><a class="dropdown-item" href="#">Grupos de Whatsapp</a></li>-->
              <li><a class="dropdown-item" href="https://legend-whimsey-f5a.notion.site/Manual-Sitio-CAU-versi-n-beta-56fd773cab744f2d94adca4baf85d503">Manual del Sitio</a></li>
            </ul>
          </li>
          <!--
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle disabled" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Docencia
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#">Mis Cursos</a></li>
              <li><a class="dropdown-item disabled" href="#">Cursos Abiertos</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item disabled" href="#">Material de Cursos? o dejarlo dentro de mis cursos</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" aria-current="page" href="#">Socio</a>
          </li>
          -->
        </ul>
        <ul class="nav navbar-nav my-2 my-lg-0">
          {% if user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="text-transform: capitalize"> 
                <i class="fas fa-user-alt"></i> {{ user.username }}
              </a>
              <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="{% url 'account_data' %}"></i>Perfil de Usuario</a></li>
                <li><a class="dropdown-item" href="{% url 'emergencycontacts_data' %}"></i>Contactos de Emergencia</a></li>
                <li><a class="dropdown-item" href="{% url 'medical_data' %}"></i>Información Médica</a></li>
                <li><a class="dropdown-item" href="{% url 'cars_data' %}"></i>Vehículo(s)</a></li>
                <li><a class="dropdown-item" href="{% url 'friends_data' %}"></i>Amigos Externos</a></li>
                <li><a class="dropdown-item" href="{% url 'logout'%}?next={{request.path}}"><i class="fas fa-sign-out-alt"></i> Cerrar Sesión</a></li>
              </ul>
            </li>
          {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'login'%}?next={{request.path}}"><i class="fas fa-sign-in-alt"></i> Iniciar Sesión</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>